name: FTP Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Install telnet
        run: |
          sudo apt-get update
          sudo apt-get install -y telnet netcat-openbsd

      - name: Test FTP Port
        run: |
          nc -vz server77s.irwebspace.com 21

      - name: Raw FTP Test
        run: |
          timeout 20 bash -c 'cat < /dev/null > /dev/tcp/server77s.irwebspace.com/21'
